version: "3.7"

services:
  postgres:
    image: postgres:12.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=livecontrol
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/

volumes:
  postgres:
